services:
  order.api:
    image: order.api
    build:
      context: .
      dockerfile: Order.Api/Dockerfile

  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
