services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  order.api:
    image: order.api
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
