name: eshop
networks:
  eshop-net:

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    # container_name: KULLANMA (CI'da çakışma yapar)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [eshop-net]

  order.api:
    image: ${DOCKER_NS:-samt51}/order:${VERSION:-latest}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    restart: unless-stopped
    networks: [eshop-net]

  payment.api:
    image: ${DOCKER_NS:-samt51}/payment:${VERSION:-latest}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    restart: unless-stopped
    networks: [eshop-net]

  basket.api:
    image: ${DOCKER_NS:-samt51}/basket:${VERSION:-latest}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    restart: unless-stopped
    networks: [eshop-net]

  catalog.apii:          # isim senin istediğin gibi
    image: ${DOCKER_NS:-samt51}/catalog:${VERSION:-latest}
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    restart: unless-stopped
    networks: [eshop-net]
