name: eshopsln

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      # Artık tüm servisler 'eshop/eshop' ile bağlanacak
      RABBITMQ_DEFAULT_USER: eshop
      RABBITMQ_DEFAULT_PASS: eshop
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [eshop-net]

  apigw:
    image: samt51/apigw:latest
    build:
      context: .
      dockerfile: EShop.Gateway/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
    ports: ["8080:8080"]
    depends_on:
      rabbitmq: { condition: service_healthy }
      order.api: { condition: service_started }
      payment.api: { condition: service_started }
      catalog-api: { condition: service_started }
      basket.api: { condition: service_started }
    restart: unless-stopped
    networks: [eshop-net]

  order.api:
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
    image: samt51/order:latest
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:3434
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: eshop   # guest yerine eshop
      RabbitMQ__Password: eshop
      RabbitMQ__VirtualHost: /
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: [ "3434:3434" ]
    networks: [ eshop-net ]

  payment.api:
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
    image: samt51/payment:latest
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:3536
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: eshop
      RabbitMQ__Password: eshop
      RabbitMQ__VirtualHost: /
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: [ "3536:3536" ]
    networks: [ eshop-net ]

  catalog-api:
    build:
      context: .
      dockerfile: ./Catalog.Apii/Dockerfile
    image: samt51/catalog:latest
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5018
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: eshop
      RabbitMQ__Password: eshop
      RabbitMQ__VirtualHost: /
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: [ "5018:5018" ]
    networks:
      eshop-net:
        aliases: [ catalog.apii ]

  basket.api:
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    image: samt51/basket:latest
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5151
      RabbitMQUrl: rabbitmq
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Username: eshop
      RabbitMQ__Password: eshop
    depends_on:
      rabbitmq: { condition: service_healthy }
    ports: ["5151:5151"]
    networks: [eshop-net]

networks:
  eshop-net:
    external: true
    name: eshopsln_eshop-net
